package Views;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Locale;

public class CoreView {
    private final ArrayList<JRadioButton> lightsRadioButtons = new ArrayList<>();
    private JPanel windowPanels;
    private JPanel
            topLevelPane; // Needs to be bound to a field for the Form Builder to build CoreView JFrame
    private JScrollPane scrollPane;
    private JPanel outsideDoorPanel;
    private JPanel lightsPanel;
    private JRadioButton turnOnRadioButton;
    private JRadioButton turnOffRadioButton;
    private JPanel wrapPan;

    public CoreView() {
        this.scrollPane.getVerticalScrollBar().setUnitIncrement(18); //Helps scroll faster
    }

    public void displayWindowSection(
            ArrayList<JLabel> labels,
            ArrayList<JRadioButton> openBtns,
            ArrayList<JRadioButton> closeBtns,
            ArrayList<JCheckBox> obstructBtns) {

        this.windowPanels.setLayout(new GridLayout(0, 4, 1, 20));
        this.windowPanels.setBorder(BorderFactory.createEmptyBorder(10, 0, 0, 0));

        // labels ArrayList same length as buttons ArrayList
        for (int i = 0; i < labels.size(); i++) {
            this.windowPanels.add(labels.get(i));
            this.windowPanels.add(openBtns.get(i));
            this.windowPanels.add(closeBtns.get(i));
            this.windowPanels.add(obstructBtns.get(i));
        }
    }

    public void addTurnOnAutoLightsListener(ActionListener listener) {
        this.turnOnRadioButton.addActionListener(listener);
    }

    public void addTurnOffAutoLightsListener(ActionListener listener) {
        this.turnOffRadioButton.addActionListener(listener);
    }

    public void displayOutsideDoorsSection(
            ArrayList<JLabel> labels,
            ArrayList<JRadioButton> lockBtns,
            ArrayList<JRadioButton> unlockBtns) {

        this.outsideDoorPanel.setLayout(new GridLayout(0, 3, 1, 20));
        this.outsideDoorPanel.setBorder(BorderFactory.createEmptyBorder(10, 0, 0, 0));

        // labels ArrayList same length as buttons ArrayList
        for (int i = 0; i < labels.size(); i++) {
            this.outsideDoorPanel.add(labels.get(i));
            this.outsideDoorPanel.add(lockBtns.get(i));
            this.outsideDoorPanel.add(unlockBtns.get(i));
        }
    }

    public void displayLightsSection(
            ArrayList<JLabel> labels,
            ArrayList<JRadioButton> onBtns,
            ArrayList<JRadioButton> offBtns,
            boolean autoLightStatus) {

        this.lightsPanel.setLayout(new GridLayout(0, 3, 1, 20));
        this.lightsPanel.setBorder(BorderFactory.createEmptyBorder(10, 0, 0, 0));

        // labels ArrayList same length as buttons ArrayList
        for (int i = 0; i < labels.size(); i++) {
            this.lightsPanel.add(labels.get(i));
            this.lightsPanel.add(onBtns.get(i));
            this.lightsPanel.add(offBtns.get(i));
        }

        this.lightsRadioButtons.addAll(onBtns);
        this.lightsRadioButtons.addAll(offBtns);

        if (autoLightStatus) {
            this.turnOnRadioButton.setSelected(true);
        } else {
            this.turnOffRadioButton.setSelected(true);
        }
    }

    /**
     * Sets the status of all the radio buttons that are responsible for manually controlling the
     * lights in each room
     *
     * @param newStatus True will enable all the Radio Buttons; False will disable them
     */
    public void setLightButtonStatus(boolean newStatus) {
        if (newStatus) {
            for (JRadioButton lightButton : this.lightsRadioButtons) {
                lightButton.setEnabled(true);
            }
        } else {
            for (JRadioButton lightButton : this.lightsRadioButtons) {
                lightButton.setEnabled(false);
            }
        }
    }

    public JPanel getWrapper() {
        return this.topLevelPane;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        topLevelPane = new JPanel();
        topLevelPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        scrollPane = new JScrollPane();
        topLevelPane.add(scrollPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        wrapPan = new JPanel();
        wrapPan.setLayout(new GridLayoutManager(9, 1, new Insets(5, 5, 0, 0), -1, -1));
        scrollPane.setViewportView(wrapPan);
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Fira Code", Font.BOLD, 16, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Windows");
        wrapPan.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        windowPanels = new JPanel();
        windowPanels.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        wrapPan.add(windowPanels, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JSeparator separator1 = new JSeparator();
        wrapPan.add(separator1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        outsideDoorPanel = new JPanel();
        outsideDoorPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        wrapPan.add(outsideDoorPanel, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$("Fira Code", Font.BOLD, 16, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setText("Outside Doors");
        wrapPan.add(label2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator2 = new JSeparator();
        wrapPan.add(separator2, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$("Fira Code", Font.BOLD, 16, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setText("Lights");
        wrapPan.add(label3, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lightsPanel = new JPanel();
        lightsPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        wrapPan.add(lightsPanel, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        wrapPan.add(panel1, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel1.setBorder(BorderFactory.createTitledBorder(null, "Automatic Lights", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        turnOnRadioButton = new JRadioButton();
        turnOnRadioButton.setText("Turn On");
        panel1.add(turnOnRadioButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        turnOffRadioButton = new JRadioButton();
        turnOffRadioButton.setText("Turn Off");
        panel1.add(turnOffRadioButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(turnOffRadioButton);
        buttonGroup.add(turnOnRadioButton);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topLevelPane;
    }

}
