package Views;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.jdatepicker.impl.JDatePickerImpl;

/**
 * The type Dash.
 */
public class Dash extends JFrame {
  /**
   * The Stop simulation button.
   */
  JButton toggleSimulationButton;
  /**
   * The Edit action button.
   */
  JButton editSimulationButton;
  /**
   * The Tabbed pane 1.
   */
  JTabbedPane tabbedPane1;
  /**
   * The P 1.
   */
  JPanel p1;
  /**
   * The Sp 1.
   */
  JScrollPane sp1;
  /**
   * The Sp 2.
   */
  JScrollPane sp2;
  /**
   * The Tab 2.
   */
  JPanel Tab2;
  /**
   * The Tab 1.
   */
  JPanel Tab1;

  /**
   * The User profile drop down.
   */
  JComboBox userProfileDropDown; // Current User Profile

  /**
   * The User room drop down.
   */
  JComboBox userRoomDropDown; // Current User Profile's Room

  /**
   * The Date field.
   */
  JLabel dateField; // Date field

  /**
   * The Time field.
   */
  JLabel timeField; // Time Field

  /**
   * The Temp spinner.
   */
  JSpinner tempSpinner; // temperature spinner
  private JComboBox timeSpeed;
  private JButton confirmTimeSpeed;

  /**
   * The Date picker.
   */
  JDatePickerImpl datePicker;

  /**
   * The Time spinner.
   */
  JSpinner time_spinner;

  /**
   * The Time confirm.
   */
  JButton timeConfirm;

  private int hour;
  private int minute;
  private int second;
  private String amPM;
  private boolean simRunning = false;

  /**
   * Instantiates a new Dashboard frame.
   *
   * @param temp the temp
   * @param date the date
   * @param time the time
   */
  public Dash(int temp, String date, String time) {
    tempSpinner.setValue(temp);
    dateField.setText(date);
    timeField.setText(time);
    timeConfirm = new JButton("OK");
    tabbedPane1.addMouseListener(
            new MouseAdapter() {
              @Override
              public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
              }
            });

    Timer timer = new Timer(1000, new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        String hourString;
        String minuteString;
        String secondString;

        second++;
        if (second > 59) {
          minute++;
          second = 0;
        }
        if (minute > 59) {
          hour++;
          minute = 0;
        }
        if (hour > 12) {
          hour = 1;
          if (amPM == "AM")
            amPM = "PM";
          else
            amPM = "AM";
        }

        if (hour < 10)
          hourString = "0" + hour;
        else
          hourString = String.valueOf(hour);

        if (minute < 10)
          minuteString = "0" + minute;
        else
          minuteString = String.valueOf(minute);

        if (second < 10)
          secondString = "0" + second;
        else
          secondString = String.valueOf(second);

        String time = hourString + ":" + minuteString + ":" + secondString + " " + amPM;
        timeField.setText(time);
      }
    });

    toggleSimulationButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        if (simRunning == true) {
          timer.stop();
          simRunning = false;
        } else {
          hour = Integer.parseInt(timeField.getText().substring(0, 2));
          minute = Integer.parseInt(timeField.getText().substring(3, 5));
          second = Integer.parseInt(timeField.getText().substring(6, 8));
          amPM = timeField.getText().substring(8);
          timer.restart();
          simRunning = true;
        }
      }
    });
    confirmTimeSpeed.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {

        if (timeSpeed.getSelectedItem().toString() == "10x")
          timer.setDelay(100);
        else if (timeSpeed.getSelectedItem().toString() == "100x")
          timer.setDelay(10);
        else
          timer.setDelay(1000);
      }
    });
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    p1 = new JPanel();
    p1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
    p1.setPreferredSize(new Dimension(600, 600));
    sp1 = new JScrollPane();
    p1.add(sp1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new GridLayoutManager(8, 4, new Insets(0, 0, 0, 0), -1, -1));
    sp1.setViewportView(panel1);
    toggleSimulationButton = new JButton();
    toggleSimulationButton.setText("Start Simulation");
    panel1.add(toggleSimulationButton, new GridConstraints(0, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    editSimulationButton = new JButton();
    editSimulationButton.setText("Edit Simulation");
    panel1.add(editSimulationButton, new GridConstraints(1, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    userProfileDropDown = new JComboBox();
    final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
    userProfileDropDown.setModel(defaultComboBoxModel1);
    panel1.add(userProfileDropDown, new GridConstraints(2, 0, 1, 4, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    userRoomDropDown = new JComboBox();
    final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
    userRoomDropDown.setModel(defaultComboBoxModel2);
    panel1.add(userRoomDropDown, new GridConstraints(3, 0, 1, 4, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    dateField = new JLabel();
    dateField.setText("");
    panel1.add(dateField, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    timeField = new JLabel();
    timeField.setText("");
    panel1.add(timeField, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    final JLabel label1 = new JLabel();
    label1.setText("Date");
    panel1.add(label1, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JLabel label2 = new JLabel();
    label2.setText("Time");
    panel1.add(label2, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    tempSpinner = new JSpinner();
    panel1.add(tempSpinner, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JLabel label3 = new JLabel();
    label3.setText("Time Speed");
    panel1.add(label3, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    confirmTimeSpeed = new JButton();
    confirmTimeSpeed.setText("OK");
    panel1.add(confirmTimeSpeed, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JLabel label4 = new JLabel();
    label4.setText("Outside Temperature");
    panel1.add(label4, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    timeSpeed = new JComboBox();
    final DefaultComboBoxModel defaultComboBoxModel3 = new DefaultComboBoxModel();
    defaultComboBoxModel3.addElement("1x");
    defaultComboBoxModel3.addElement("10x");
    defaultComboBoxModel3.addElement("100x");
    timeSpeed.setModel(defaultComboBoxModel3);
    panel1.add(timeSpeed, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    sp2 = new JScrollPane();
    p1.add(sp2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    final JPanel panel2 = new JPanel();
    panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    sp2.setViewportView(panel2);
    tabbedPane1 = new JTabbedPane();
    panel2.add(tabbedPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
    Tab1 = new JPanel();
    Tab1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    tabbedPane1.addTab("Tab1", Tab1);
    Tab2 = new JPanel();
    Tab2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    tabbedPane1.addTab("Tab2", Tab2);
    final JPanel panel3 = new JPanel();
    panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    tabbedPane1.addTab("+", panel3);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return p1;
  }

}
